notifications:
  email: false

env:
  global:
  - TERM=dumb

language: java
jdk: oraclejdk8

service:
- docker

addons:
  apt:
    packages:
    - bash
    - curl
    - docker-ce
    - python-pip

install: true
before_install:
- sudo pip install docker-compose httpie >/dev/null 2>&1
#
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 80 8080 >/dev/null

script:
- export root=$(pwd)
- ./mvnw >/dev/null
- ./gradlew composeUp
- http :8080/app/
- http :8080/app/dwr/index.html
- ./gradlew composeDown

before_cache:
- for item in $(find ~/.gradle -name "*.lock");
    do sudo rm -rf $item ;
  done

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  - $HOME/.docker
